// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBA3u_LRxHR2zj6kbDW7qONwl-LJClR4',
    appId: '1:92923107737:web:84f4ae03cb06217056db08',
    messagingSenderId: '92923107737',
    projectId: 'tubes-unique',
    authDomain: 'tubes-unique.firebaseapp.com',
    storageBucket: 'tubes-unique.appspot.com',
    measurementId: 'G-KNF8MMDV47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfZE9bRPELl7rlGMnUpWlcme6VW_Ymqr8',
    appId: '1:92923107737:android:9b250bb2b6ad4eef56db08',
    messagingSenderId: '92923107737',
    projectId: 'tubes-unique',
    storageBucket: 'tubes-unique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1qB0UJ7Q4zifvPIP5ykkX7DSaFDJYBU',
    appId: '1:92923107737:ios:87bd4806fb10492156db08',
    messagingSenderId: '92923107737',
    projectId: 'tubes-unique',
    storageBucket: 'tubes-unique.appspot.com',
    iosBundleId: 'com.example.tubesUnique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1qB0UJ7Q4zifvPIP5ykkX7DSaFDJYBU',
    appId: '1:92923107737:ios:87bd4806fb10492156db08',
    messagingSenderId: '92923107737',
    projectId: 'tubes-unique',
    storageBucket: 'tubes-unique.appspot.com',
    iosBundleId: 'com.example.tubesUnique',
  );
}
